import time
print ("Selamat datang di DarkPulsa")
print ("By : Gio")
time.sleep(1.0)
print ("Masukkan Jumlah Dengan Format Contoh : 100.000")
jumlah = input ("Silahkan Masukkan Jumlah: ")
jumlah = str(jumlah)
print ("Masukkan Nomor Dengan Format Contoh : +6200000000")
nomor = input ("Silahkan Masukkan Nomor : ")
nomor = str(nomor)
print ("Sedang di Proses...")
time.sleep(3.0)
print ("Nomor :", nomor)
time.sleep(1.0)
print ("Jumlah :", jumlah)
time.sleep(1.0)
print ("Tunggu Sebentar...")
time.sleep(5.0)
print ("Berhasil!, Silahkan Tunggu 5 Menit")
